
name: Run EZOut
on: 
  push: 
jobs: 
  RunEZOut: 
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps: 
      - name: Check out repository
        uses: actions/checkout@v2
      - name: UseEZOut
        uses: StartAutomating/EZOut@master
      - name: Push Changes
        shell: pwsh
        run: git push; exit 0

