
name: ugit-psa
on: 
  workflow_dispatch: 
jobs: 
  SendPSA: 
    name: PSA
    uses: StartAutomating/PSA@main
    id: PSA
env: 
  AT_PROTOCOL_HANDLE: mrpowershell.bsky.social
  AT_PROTOCOL_APP_PASSWORD: ${{ secrets.AT_PROTOCOL_APP_PASSWORD }}
