
name: Run HelpOut
on: 
  push: 
jobs: 
  HelpOut: 
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps: 
      - name: Check out repository
        uses: actions/checkout@v2
      - name: UseHelpOut
        uses: StartAutomating/HelpOut@master

